version: "3"
services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    container_name: magreenlife-backend
    restart: always
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    container_name: magreenlife-frontend
    restart: always
    depends_on:
      - backend
